define({
    root : {
        ndvi_label: 'NDVI',
        error: 'WSP UI Error',
        z_score: 'ZScore',
        anomaly: 'Anomaly AVG',
        anomaly_dpy: 'Anomaly DPY',
        rainfall: 'Rainfall',
        copyright: '© FAO 2015',
        temperature: 'Temperature',
        wsp: 'Water Scarcity Platform',
        evapotranspiration: 'Evapotranspiration',
        please_select: 'Please select a layer...',
        country_coundaries: 'Country Boundaries',
        wheat: 'Wheat (Cultivated Area)',
        population_landscan: 'Population (2012)',
        rainfed_land_gaez: 'Rainfed Land GAEZ (2010)',
        irrigated_areas_solaw_2012: 'Irrigated Areas (2012)',
        cultivated_land_gaez_2010: 'Cultivated Land GAEZ (2010)',
        chirps: 'Rainfall',
        selectable_layers: 'Layers',
        eco_region: 'ECO Region',
        gaul1: 'ADM. Unit Level1 (AFG)',
        hotspot: 'HotSpot (AFG) > -30%',
        wheat_area: 'Wheat Area (AFG)',
        zonalstats_gaul1: 'Zonalstats ADM1 (AFG)',
        province: 'Province',
        area_cultivated: 'Area cultivated (ha)',
        area_affected: 'Area affected (ha)',
        area_percentage: 'Area affected (%)',
        zonalStatisticsTitle: 'ZonalStatistics Administrative Unit Level1 (Afghanistan)'
    },
    fr : true,
    es : true
});